---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  data_bags_path: test/data_bags

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[odi-cert-deployer::default]
    attributes:
      cert:
        name: xero
        file: privatekey.pem
